version: 'v001'
versionServicePackager: 'v001'
pollingTimeMinutes: 2

chatNamespace: xesoft_chat
chatSversionServiceChat: v001
#chatRedisHost: localhost
#chatRedisPort: 6379
chatTTLInH: 48
chatMaxLengthMsg: 200

# LOG
logging:
  level: INFO
  loggers:
    chat: DEBUG
  appenders:
    - type: console

# AWS COGNITO
awsServiceRegion:
awsUserPoolId:
awsClientId:
awsPoolSecret:
awsJwks:

# AWS DYNAMO
awsDynamoChatHistoryTableName: chat-history
awsDynamoChatRegion: eu-west-1
awsDynamoSessionCountTtl: 300
awsDynamoIpInfoTtl: 864000