export const HTTP = 'http';					// local
// export const HTTP = 'https';				// aws
export const WS = 'ws';						// local
// export const WS = 'wss';					// aws
export const HOSTNAME = 'localhost';		// local
// export const HOSTNAME = 'www.xesoft.ml';	// aws
export const REST_PORT = '8443';			// local
// export const REST_PORT = '8443';			// aws
export const CHAT_PORT = '9443';			// local
// export const CHAT_PORT = '9443';			// aws
